core_app/urls.py
from django.urls import path
from . import views

app_name = 'core_app'

urlpatterns = [
    path('', views.home_view, name='home'),
    # path('instructions/', views.instructions_view, name='instructions'),
    path('success/', views.success_view, name='success'),
    # path('terms_and_conditions/', views.terms_view, name='terms'),
    # path('data_policy/', views.privacy_view, name='privacy'),
    # path('legal_notice/', views.legal_view, name='legal'),
    # path('funding/', views.funding_view, name='funding'),
    path('protocols/', views.protocols_view, name='protocols'),
    path('contact/', views.contact_view, name='contact'),
    # path('information/', views.information_view, name='information'),
    path('download/<filename>/', views.download_pdf, name='download'),
    path('about_us/', views.about_view, name='about'),
    path('search_job/', views.search_view, name='search-job'),
    path('sample/<uuid:sample_id>/', views.sample_view, name='sample-detail'),
    path('tutorial/', views.tutorial_view, name='tutorial'),
    path('browser/', views.browser_view, name='browser'),
]

workflow/urls.py
from django.urls import path
from . import views

app_name = 'workflow'

urlpatterns = [
    path('upload_data/', views.workflow_view, name='upload_data'),
    path('sample/<uuid:sample_id>/pdf/', views.download_report, name='download_report'),
    path('admin/sample/<uuid:sample_id>/pdf/', views.admin_report_pdf, name='admin_report'),
]

core_app/models.py
from django.db import models


class Contact(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()

    def __str__(self):
        return self.email

core_app/forms.py
from django import forms
from django.forms import ModelForm
from .models import Contact

from django.utils.safestring import mark_safe


class InstructionsForm(forms.Form):

    check2 = forms.BooleanField(label="The sample has more than 70% viable tumor cell content.", required=True)

    check3 = forms.BooleanField(label="Analyse only one sample in each qPCR experiment.", required=True)

    check4 = forms.BooleanField(label="The sample has been analysed in one of the following qPCR Thermocycle: "
                                      "Applied Biosystems 7500, QS1, QS3, QS5 or QS6.", required=True)

    check5 = forms.BooleanField(label="The following names have been assigned to the SNP primers: "
                                "cg18849583, cg01268345, cg10333416, cg12925355, cg25542041 and cg02227036.", required=True)

    check6 = forms.BooleanField(label="Upload a txt file that contains the results.", required=True)

    check8 = forms.BooleanField(label="Avoid using personal patient information in the sample identifier such as name, "
                                      "gender or nationality.", required=True)


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

    check_box = forms.BooleanField(label=mark_safe('I have read and accept that my data will be the responsibility of the '
                                         'Fundació Sant Joan de Déu · Institut de Recerca Sant Joan de Déu on '
                                         'the legal basis of consent. The data will not be transferred to third '
                                         'parties. For more information or how to exercise your rights, '
                                         'you can consult the <a href="https://www.irsjd.org/en/legal-notice-and-terms-of-use/" target="_blank" rel="noopener noreferrer">terms of use</a> and '
                                        '<a href="https://www.irsjd.org/en/privacy-policy/" target="_blank" rel="noopener noreferrer">privacy policy</a>'), required=True)

core_app/views.py
import mimetypes
import os

from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.core.mail import EmailMessage
from django.core.exceptions import ValidationError

from .forms import InstructionsForm, ContactForm
from workflow.models import Sample, Calibration, Classification


def home_view(request):
    return render(request, 'core_app/home.html')


def protocols_view(request):
    return render(request, 'core_app/protocols.html')


def terms_view(request):
    return render(request, 'core_app/terms.html')


def privacy_view(request):
    return render(request, 'core_app/privacy.html')


def legal_view(request):
    return render(request, 'core_app/legal.html')


def funding_view(request):
    return render(request, 'core_app/funding.html')


def success_view(request):
    job_id = request.GET.get('job_id')
    sample = get_object_or_404(Sample, id=job_id)
    return render(request, 'core_app/success.html', context={'job_id': sample.id})


def information_view(request):
    return render(request, 'core_app/information.html')


def tutorial_view(request):
    return render(request, 'core_app/tutorial.html')


def browser_view(request):
    return render(request, 'core_app/browser.html')


def about_view(request):
    return render(request, 'core_app/about_us.html')


def instructions_view(request):
    if request.method == 'POST':
        form = InstructionsForm(request.POST)
        if form.is_valid():
            return redirect('workflow:upload_data')
    else:
        form = InstructionsForm()
    return render(request, 'core_app/instructions.html', {'form': form})


def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            email_subject = f'New contact {form.cleaned_data["email"]}: {form.cleaned_data["subject"]}'
            email_message = form.cleaned_data['message']
            email = EmailMessage(email_subject, email_message, 'hospitalbarcelona.PECA@sjd.es',
                                 ['joshua.llano@upc.edu'])
            email.send()
            return render(request, 'core_app/success_contact.html')
    form = ContactForm()
    context = {'form': form}
    return render(request, 'core_app/contact.html', context)


def download_pdf(request, filename):
    if filename != '':
        # Define Django project base directory
        BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        # Define the full file path
        filepath = BASE_DIR + '/static/protocols/' + filename
        # Open the file for reading content
        path = open(filepath, 'rb', buffering=0)
        # Set the mime type
        mime_type, _ = mimetypes.guess_type(filepath)
        # Set the return value of the HttpResponse
        response = HttpResponse(path, content_type=mime_type)
        # Set the HTTP header for sending to browser
        response['Content-Disposition'] = "attachment; filename=%s" % filename
        # Return the response value
        return response
    else:
        return render(request, 'core_app/protocols.html')


def search_view(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        if searched:
            return redirect('core_app:sample-detail', sample_id=searched)
        else:
            return render(request, 'core_app/search_job_id.html')
    else:
        return redirect('core_app:home')


def sample_view(request, sample_id):
    try:
        sample = get_object_or_404(Sample, id=sample_id)
        classification = get_object_or_404(Classification, sample=sample)
        calibration = get_object_or_404(Calibration, sample=sample)
        return render(request, 'core_app/sample_detail.html', {'sample': sample, 
                                                            'classification': classification, 
                                                            'calibration': calibration})
    except ValidationError:
        raise Http404("Job ID is not valid")

templates/core_app/browser.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="col-md-12">
        <h3 class="mb-3">Browser compatibility</h3>
        <hr>
        <div class="text-center">
            <table class="table table-hover table-bordered table-sm align-middle">
                <thead>
                <tr>
                    <th scope="col"><b>OS</b></th>
                    <th scope="col"><b>Version</b></th>
                    <th scope="col"><b>Chrome</b></th>
                    <th scope="col"><b>Firefox</b></th>
                    <th scope="col"><b>Microsoft Edge</b></th>
                    <th scope="col"><b>Safari</b></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td style="font-weight: bold;">Linux</td>
                    <td>Ubuntu 22</td>
                    <td>119</td>
                    <td>120</td>
                    <td>n/a</td>
                    <td>n/a</td>
                </tr>
                <tr>
                    <td style="font-weight: bold;">MacOS</td>
                    <td>Ventura</td>
                    <td>119</td>
                    <td>n/a</td>
                    <td>n/a</td>
                    <td>16</td>
                </tr>
                <tr>
                    <td style="font-weight: bold;">Windows</td>
                    <td>11</td>
                    <td>119</td>
                    <td>98</td>
                    <td>119</td>
                    <td>n/a</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/core_app/contact.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="col-md-12">
        <h3 class="mb-3">Contact</h3>
        <hr>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-12 mb-2">
                    {{ form.first_name|as_crispy_field  }}
                </div>
                <div class="col-md-12 mb-2">
                    {{ form.last_name|as_crispy_field  }}
                </div>
                <div class="col-md-12 mb-2">
                    {{ form.email|as_crispy_field  }}
                </div>
                <div class="col-md-12 mb-2">
                    {{ form.subject|as_crispy_field  }}
                </div>
                <div class="col-md-12 mb-2">
                    {{ form.message|as_crispy_field  }}
                </div>
                <div class="col-md-12 mb-2">
                    {{ form.check_box|as_crispy_field  }}
                </div>
            </div>
            <button class="btn btn-primary btn-lg btn-block mb-3" type="submit">Submit</button>
        </form>
    </div>
{% endblock %}

templates/core_app/funding.html
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="col-md-12">
        <h3 class="mb-3">Funding</h3>
        <hr>
        <div class="row">
            <div class="col col-md-auto px-4">
                <p><h4>This project has been developed by:</h4></p>
                <p>Bioinformatics and Biomedical Signals Laboratory (B2SLAB)</p>
                <div class="container pb-3" style="text-align: center;"><a href="http://b2slab.upc.edu/" target="_blank" rel="noopener noreferrer"><img src="{% static 'img/logos/b2slab.png' %}" alt="Logo B2SLAB" height="100px"></a></div>
                <p>Translational Genomics</p>
                <div class="container pb-3" style="text-align: center;"><a href="https://www.irsjd.org/en/research/39/translational-genomics/" target="_blank" rel="noopener noreferrer"><img src="{% static 'img/logos/TraslationalGenomics.png' %}" alt="Logo TG" height="100px"></a></div>
            </div>
            <div class="col col-md-auto px-4">
                <p><h4>This work is supported by:</h4></p>
                <p>The Spanish Government [Instituto de Salud Carlos III]</p>
                <div class="container pb-3" style="text-align: center;"><a href="https://www.isciii.es/Paginas/Inicio.aspx" target="_blank" rel="noopener noreferrer"><img src="{% static 'img/logos/isciii.jpg' %}" alt="Logo ISCIII" height="100px"></a></div>
                <p>The Fundació La Marató de TV3</p>
                <div class="container pb-3" style="text-align: center;"><a href="https://www.ccma.cat/tv3/marato/en/fundacio/" target="_blank" rel="noopener noreferrer"><img src="{% static 'img/logos/marato.png' %}" alt="Logo MaratoTV3" height="75px"></a></div>
                <p>Association of families and friends of patients with Neuroblastoma <br> (NEN association)</p>
                <div class="container pb-3" style="text-align: center;"><a href="http://asociacion-nen.org/" target="_blank" rel="noopener noreferrer"><img src="{% static 'img/logos/nen.png' %}" alt="Logo NEN" height="120px"></a></div>
                <p>Barcelona Sant Joan de Déu Children’s Hospital</p>
                <div class="container pb-3" style="text-align: center;"><a href="https://www.sjdhospitalbarcelona.org/en" target="_blank" rel="noopener noreferrer"><img src="{% static 'img/logos/hsjd.png' %}" alt="Logo HSJD" height="75px"></a></div>
            </div>
        </div>
    </div>
{% endblock %}

templates/core_app/home.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="col-md-12">
        <h3 class="mb-3">Home</h3>
        <hr>
        <div class="mb-3" style="text-align: justify;">
            <p>EpiGe-App (Epigenetic Genotyping Application) is an interactive, 
            user-friendly web application for the classification of medulloblastoma WNT, SHH or non-WNT/non-SHH subgroups 
            directly from quantitative PCR (qPCR) data <a href="{% url 'core_app:protocols' %}#protocols">(please see Quantitative 
            PCR-based, methyl-genotyping assay protocol)</a>. The basis of this classification strategy is the analysis of the 
            methylation profile of a previously validated panel of six CpG sites with distinctive, subgroup-specific 
            methylation profiles <a href="https://pubmed.ncbi.nlm.nih.gov/29351917/" target="_blank" 
            rel="noopener noreferrer">(Gomez et al Clinical Cancer research 2018)</a>. The obtained raw qPCR data can 
            be directly uploaded onto the EpiGe-App for automated interpretation of methylation status and subsequent 
            subgroup prediction the methylation class of a medulloblastoma tumour. For further details, please 
            <a href="https://www.sciencedirect.com/science/article/pii/S2589004223016759" 
            target="_blank" rel="noopener noreferrer">Gómez et al iScience 2023</a>.
            </p>
        </div>
        <div class="alert alert-danger" role="alert">
            <p class="pb-0 mb-0" style="text-align: justify;">
                <i class="fa-solid fa-triangle-exclamation mr-1"></i> 
                EpiGe-App is a research tool that is intended only for scientific purposes: the EpiGe-App 
                has not been validated clinically and was not designed for diagnostics purpose, nor to replace 
                the services of a licensed, trained physician or health professional, or to substitute for medical advice.
            </p>
        </div>
        <div class="alert alert-primary" role="alert">
            <p><i class="fa-solid fa-circle-info mr-1"></i> 
                This website is <b>free</b> and <b>open</b> to all users and there is <b>no login</b> requirement.
            </p>
            <p><i class="fa-solid fa-cookie-bite mr-1"></i> 
                This webserver only uses <b>technical cookies</b>. If you continue to use EpiGe-App, 
                we will assume that you agree to receive cookies from this website.
            </p>
            <p class="pb-0 mb-0">
                <i class="fa-solid fa-shield-halved mr-1"></i> 
                Data uploaded to this website will only be stored in order to 
                conduct the requested analyses. After <b>30 days</b> the results and data 
                of an analysis will be deleted. Please consult 
                <a href="https://www.irsjd.org/en/privacy-policy/" target="_blank" 
                rel="noopener noreferrer" class="alert-link">this page</a> 
                to get more information about data protection.
            </p>
        </div>
        <a class="btn btn-success btn-lg btn-block" href="{% url 'workflow:upload_data' %}" role="button">RUN ANALYSIS</a>
    </div>
{% endblock %}

templates/core_app/information.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="col-md-12">
        <h3 class="mb-3">Graphical Abstract</h3>
        <hr>
        <div class="container pb-3" style="text-align: center;">
            <img src="{% static 'img/EpiGe_iScience_GraphicalAbstract.png' %}" alt="Graphical Abstract" height="750px">
        </div>
    </div>
{% endblock %}

templates/core_app/instructions.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="col-md-12">
        <h3 class="mb-3">Step II</h3>
        <hr>
        <h4 class="mb-3">Requirements and conditions</h4>
        <p>To proceed with the analysis you must accept the following conditions:</p>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-12 mb-2">
                    {{ form.check2|as_crispy_field  }}
                </div>
                <div class="col-md-12 mb-2">
                    {{ form.check3|as_crispy_field  }}
                </div>
                <div class="col-md-12 mb-2">
                    {{ form.check4|as_crispy_field  }}
                </div>
                <div class="col-md-12 mb-2">
                    {{ form.check5|as_crispy_field  }}
                </div>
                <div class="col-md-12 mb-2">
                    {{ form.check6|as_crispy_field  }}
                </div>
                <div class="col-md-12 mb-2">
                    {{ form.check8|as_crispy_field  }}
                </div>
            </div>
            <div class="progress mb-3">
                <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%"></div>
            </div>
            <div class="alert alert-danger" role="alert">
                <i class="fa-solid fa-triangle-exclamation"></i> Classification using methylation profiling is a research tool under development, it is not verified and has not been clinically validated. Implementation of the results in a clinical setting is in the sole responsibility of the treating physician.
            </div>
            <button class="btn btn-primary btn-lg btn-block mb-3" type="submit">Next</button>
        </form>
    </div>
{% endblock %}

templates/core_app/protocols.html
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="col-md-12" style="text-align: justify;">
      <h3 class="mb-3" id="protocols">Protocols</h3>
      <hr>
      <p>Download and make sure to follow the guidelines below before proceeding:</p>
      <ul>
          <li><a href="{% url 'core_app:download' filename='EpiGe_Genotyping_Protocol.pdf' %}" target="_blank"><i class="fa-solid fa-file mr-1"></i>EpiGe_Genotyping_Protocol.pdf</a></li>
          <li><a href="{% url 'core_app:download' filename='EpiGe_Genotyping_Template.pdf' %}" target="_blank"><i class="fa-solid fa-file mr-1"></i>EpiGe_Genotyping_Template.pdf</a></li>
          <li><a href="{% url 'core_app:download' filename='EpiGe_QuantStudio_Configuration.pdf' %}" target="_blank"><i class="fa-solid fa-file mr-1"></i>EpiGe_QuantStudio_Configuration.pdf</a></li>
      </ul>
      <p>Download and make sure to use the corresponding template for your equipment:</p>
      <ul>
          <li><a href="{% static 'protocols/EpiGe_TEMPLATE_7500.edt' %}" target="_blank"><i class="fa-solid fa-file mr-1"></i>EpiGe_TEMPLATE_7500.edt</a></li>
          <li><a href="{% static 'protocols/EpiGe_TEMPLATE_Q6Flex.edt' %}" target="_blank"><i class="fa-solid fa-file mr-1"></i>EpiGe_TEMPLATE_Q6Flex.edt</a></li>
          <li><a href="{% static 'protocols/EpiGe_TEMPLATE_QS1.edt' %}" target="_blank"><i class="fa-solid fa-file mr-1"></i>EpiGe_TEMPLATE_QS1.edt</a></li>
          <li><a href="{% static 'protocols/EpiGe_TEMPLATE_QS3.edt' %}" target="_blank"><i class="fa-solid fa-file mr-1"></i>EpiGe_TEMPLATE_QS3.edt</a></li>
          <li><a href="{% static 'protocols/EpiGe_TEMPLATE_QS5.edt' %}" target="_blank"><i class="fa-solid fa-file mr-1"></i>EpiGe_TEMPLATE_QS5.edt</a></li>
      </ul>
      <h3 class="mb-3" id="materials">Materials</h3>
      <hr>
      <p>The following table shows the name of the primers, the associated CpG in the methylation arrays and the link to purchase the primer:</p>
      <table class="table table-hover">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">EpiGe_primer_ID</th>
              <th scope="col">Illumina CpG ID</th>
              <th scope="col">IDT_Primer_ID</th>
              <th scope="col">Link to purchase</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row">1</th>
              <td>G1_1884</td>
              <td>cg18849583</td>
              <td>CD.GT.WFVP0601.1</td>
              <td><a href="https://eu.idtdna.com/site/order/emailcart/SetEmailOrder?RemoteWishID=9fCZuJ1j3kw=&SpecID=3&RemoteSessionID=iBXBJAPvc4nI1AtknhoWB015dXfrqlNOIl7/eAgNULLVALpzA=" target="_blank" rel="noopener noreferrer"><i class="fa-solid fa-cart-shopping"></i></a></td>
            </tr>
            <tr>
              <th scope="row">2</th>
              <td>G3_0126</td>
              <td>cg01268345</td>
              <td>CD.GT.PVWC1084.1</td>
              <td><a href="https://eu.idtdna.com/site/order/emailcart/SetEmailOrder?RemoteWishID=LAhUY2SmrpI=&SpecID=3&RemoteSessionID=iBXBJAPvc4nI1AtknhoWB015dXfrqlNOIl7/eAgNULLVALpzA=" target="_blank" rel="noopener noreferrer"><i class="fa-solid fa-cart-shopping"></i></a></td>
            </tr>
            <tr>
              <th scope="row">3</th>
              <td>S1_1033</td>
              <td>cg10333416</td>
              <td>CD.GT.SPDR8897.10</td>
              <td><a href="https://eu.idtdna.com/site/order/emailcart/SetEmailOrder?RemoteWishID=kygjKqzHQ1A=&SpecID=3&RemoteSessionID=iBXBJAPvc4nI1AtknhoWB015dXfrqlNOIl7/eAgNULLVALpzA=" target="_blank" rel="noopener noreferrer"><i class="fa-solid fa-cart-shopping"></i></a></td>
            </tr>
            <tr>
              <th scope="row">4</th>
              <td>S3_1292</td>
              <td>cg12925355</td>
              <td>CD.GT.GYJV9231.1</td>
              <td><a href="https://eu.idtdna.com/site/order/emailcart/SetEmailOrder?RemoteWishID=mAnXRNULLVALdByJ8=&SpecID=3&RemoteSessionID=iBXBJAPvc4nI1AtknhoWB015dXfrqlNOIl7/eAgNULLVALpzA=" target="_blank" rel="noopener noreferrer"><i class="fa-solid fa-cart-shopping"></i></a></td>
            </tr>
            <tr>
              <th scope="row">5</th>
              <td>W1_2554</td>
              <td>cg25542041</td>
              <td>CD.GT.JBHB3172.1</td>
              <td><a href="https://eu.idtdna.com/site/order/emailcart/SetEmailOrder?RemoteWishID=5/K77obJlFk=&SpecID=3&RemoteSessionID=iBXBJAPvc4nI1AtknhoWB015dXfrqlNOIl7/eAgNULLVALpzA=" target="_blank" rel="noopener noreferrer"><i class="fa-solid fa-cart-shopping"></i></a></td>
            </tr>
            <tr>
              <th scope="row">6</th>
              <td>W3_0222</td>
              <td>cg02227036</td>
              <td>CD.GT.JYVK6101.1</td>
              <td><a href="https://eu.idtdna.com/site/order/emailcart/SetEmailOrder?RemoteWishID=qUwRJ6W3RAM=&SpecID=3&RemoteSessionID=iBXBJAPvc4nI1AtknhoWB015dXfrqlNOIl7/eAgNULLVALpzA=" target="_blank" rel="noopener noreferrer"><i class="fa-solid fa-cart-shopping"></i></a></td>
            </tr>
          </tbody>
        </table>
      <h3 class="mb-3" id="supplementary">Supplementary materials</h3>
      <hr>
      <p>The following file is an example of a thermal cycler generated file. This file contains amplification data from a medulloblastoma sample using the Applied Biosystems QS5 thermocycler. It can be used to test the webserver without the need for your own data.</p>
      <ul>
          <li><a href="{% static 'protocols/EpiGe_sample_example.txt' %}" target="_blank"><i class="fa-solid fa-file mr-1"></i>EpiGe_sample_test.txt</a></li>
      </ul>
      <p>The following file is an example of a report generated by the webserver. Users can download their own analysis reports, such as this one, on their results pages. For a better understanding of the results the user can consult the <a href="{% url 'core_app:tutorial' %}">tutorial</a> or read the article published in <a href="https://www.sciencedirect.com/science/article/pii/S2589004223016759" 
        target="_blank" rel="noopener noreferrer">iScience</a>.</p>
      <ul>
        <li><a href="{% static 'protocols/EpiGe_report_example.pdf' %}" target="_blank"><i class="fa-solid fa-file mr-1"></i>EpiGe_report_example.pdf</a></li>
      </ul>
    </div>
{% endblock %}

templates/core_app/search_job_id.html
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block content %}
    <h1>Hey! You forgot to search a Job ID...</h1>
{% endblock %}

templates/core_app/success.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-md-12">
        <h3 class="mb-3">Thank you for using the EpiGe-App!</h3>
        <hr>
        <div class="alert alert-danger" role="alert">
            <p class="pb-0 mb-0" style="text-align: justify;"><i class="fa-solid fa-triangle-exclamation mr-1"></i> EpiGe-App is a research tool that is intended only for scientific purposes: the EpiGe-App has not been validated clinically and was not designed for diagnostics purpose, nor to replace the services of a licensed, trained physician or health professional, or to substitute for medical advice.</p>
        </div>
        <h6>Your analysis has been assigned the following Job ID:</h6>
        <div class="my-3 text-center">
            <p class="text-justify p-2 border rounded bg-white" id="myInput" style="vertical-align: middle; display: inline-block; margin-bottom: 0;"><strong>{{ job_id }}</strong></p> 
            <button id="btn-copy" type="button" class="btn btn-secondary" onclick="CopyToClipboard('myInput');return false;" data-toggle="tooltip" data-placement="top" title="Copy to Clipboard"><i class="fa-regular fa-copy"></i></button>
        </div>
        <div class="alert alert-primary" role="alert">
            <i class="fa-solid fa-circle-info mr-1"></i>
            <strong>Please keep this code to be able to access the results of the analysis through the search engine.</strong>
        </div>
        <p class="text-justify">In case of any problem, please contact us at the following e-mail address: <a href="mailto:peca@hsjdbcn.es">peca@hsjdbcn.es</a></p>
    </div>

    <!--TODO: Describir la funcion de javascript-->
    <script>
        function CopyToClipboard(id) {
          var r = document.createRange();
          r.selectNode(document.getElementById(id));
          window.getSelection().removeAllRanges();
          window.getSelection().addRange(r);
          document.execCommand('copy');
          window.getSelection().removeAllRanges();
          // Alert the copied text
          //alert("Copied the text: " + r);
        }
    </script>

{% endblock %}

templates/core_app/success_contact.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-md-12">
        <h3 class="mb-3">Contact</h3>
        <hr>
        <h4>Thank you for your inquiry</h4>
        <p>Your contact information and message was successfully submitted.</p>
    </div>
{% endblock %}