core_app/urls.py
from django.urls import path
from . import views

app_name = 'core_app'

urlpatterns = [
    path('', views.home_view, name='home'),
    # path('instructions/', views.instructions_view, name='instructions'),
    path('success/', views.success_view, name='success'),
    # path('terms_and_conditions/', views.terms_view, name='terms'),
    # path('data_policy/', views.privacy_view, name='privacy'),
    # path('legal_notice/', views.legal_view, name='legal'),
    # path('funding/', views.funding_view, name='funding'),
    path('protocols/', views.protocols_view, name='protocols'),
    path('contact/', views.contact_view, name='contact'),
    # path('information/', views.information_view, name='information'),
    path('download/<filename>/', views.download_pdf, name='download'),
    path('about_us/', views.about_view, name='about'),
    path('search_job/', views.search_view, name='search-job'),
    path('sample/<uuid:sample_id>/', views.sample_view, name='sample-detail'),
    path('tutorial/', views.tutorial_view, name='tutorial'),
    path('browser/', views.browser_view, name='browser'),
]

workflow/urls.py
from django.urls import path
from . import views

app_name = 'workflow'

urlpatterns = [
    path('upload_data/', views.workflow_view, name='upload_data'),
    path('sample/<uuid:sample_id>/pdf/', views.download_report, name='download_report'),
    path('admin/sample/<uuid:sample_id>/pdf/', views.admin_report_pdf, name='admin_report'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <script src="https://kit.fontawesome.com/2cadd0bcd4.js" crossorigin="anonymous"></script>


    <link rel="stylesheet" type="text/css" href="{% static 'css/base_web.css' %}">

    <link rel="apple-touch-icon" sizes="180x180" href="{% static '/img/favicon_io/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static '/img/favicon_io/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static '/img/favicon_io/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static '/img/favicon_io/site.webmanifest' %}">

    <title>EpiGe-App</title>
</head>

<body class="bg-light">
<header>
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'core_app:home' %}" style="color: #EA6212;font-weight: bold;">EpiGe-App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'workflow:upload_data' %}">Run analysis</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core_app:tutorial' %}">Tutorial</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Protocols and Materials
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'core_app:protocols' %}#protocols">Protocols</a>
                        <a class="dropdown-item" href="{% url 'core_app:protocols' %}#materials">Materials</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'core_app:protocols' %}#supplementary">Suplementary materials</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      About
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'core_app:about' %}">About us</a>
                        <a class="dropdown-item" href="{% url 'core_app:contact' %}">Contact</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'core_app:browser' %}">Browser compatibility</a>
                    </div>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0 ml-auto" method=POST action="{% url 'core_app:search-job' %}">
                {% csrf_token %}
                <input class="form-control mr-sm-2" type="search" placeholder="Job ID" aria-label="Search"
                       name="searched">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit"><i class="fa-solid fa-magnifying-glass mr-1"></i>Search</button>
            </form>
        </div>
    </nav>
</header>

<main>
    <div class="py-3 text-center">
        <img class="d-block mx-auto mb-4" src="{% static 'img/logos/EpiGe-App_V4_removeBKG.png' %}" alt="Logo EpiGe-App" height="150px">
    </div>

    <div class="container">
        {% block content %}{% endblock %}
    </div>
</main>

<footer>
    <div id="footer-1" class="py-4">
        <div class="container pb-3">
            <hr>
            <p class="pb-4 text-muted text-center text-small">Fundació Sant Joan de Déu – Institut de Recerca Sant Joan de Déu. Edificio SJD Pediatric Cancer Center. Santa Rosa, 39-57 08950 Esplugues del Llobregat (Barcelona) · <a href="https://www.irsjd.org/en/" target="_blank">www.irsjd.org</a></p>
            <div class="row" style="display: flex; align-items: center; justify-content: center; text-align: center">
                <div class="col">
                    <a href="https://www.sjdhospitalbarcelona.org/en/hospital/strategic-projects/pediatric-cancer-center-barcelona" target="_blank" rel="noopener noreferrer"><img src="{% static 'img/logos/PCCB logo.png' %}" alt="logo_PCCB" style="width: 100%;display: inline-block;"></a>
                </div>
                <div class="col">
                    <a href="https://www.irsjd.org/en/" target="_blank" rel="noopener noreferrer"><img src="{% static 'img/logos/irsjd.png' %}" alt="logo_IRSJD" style="width: 90%;display: inline-block;"></a>
                </div>
                <div class="col">
                    <a href="https://www.sjdhospitalbarcelona.org/en" target="_blank" rel="noopener noreferrer"><img src="{% static 'img/logos/hsjd.png' %}" alt="logo_HSJD" style="width: 90%;display: inline-block;"></a>
                </div>
                <div class="col">
                    <a href="https://creb.upc.edu/" target="_blank" rel="noopener noreferrer"><img src="{% static 'img/logos/upc.png' %}" alt="logo_CREB" style="width: 100%;display: inline-block;"></a>
                </div>
            </div>
        </div>
    </div>
    <div id="footer-2" class="pb-3">
        <div class="container">
            <h4 class="pb-3 text-center">Funding</h4>
            <div class="row pb-3" style="display: flex; align-items: center; justify-content: center; text-align: center">
                <div class="col">
                    <a href="https://www.sjdhospitalbarcelona.org/es/colabora" target="_blank" rel="noopener noreferrer"><img src="{% static 'img/logos/EpiGe-App_Patients_V4_RemoveBKG.png' %}" alt="Logo HSJD Patients" style="width: 40%;display: inline-block;"></a>
                </div>
                <div class="col">
                    <a href="https://www.isciii.es/Paginas/Inicio.aspx" target="_blank" rel="noopener noreferrer"><img src="{% static 'img/logos/isciii.jpg' %}" alt="Logo IRSJD" style="width: 60%;display: inline-block;"></a>
                </div>
                <div class="col">
                    <a href="https://www.ccma.cat/tv3/marato/en/fundacio/" target="_blank" rel="noopener noreferrer"><img src="{% static 'img/logos/marato.png' %}" alt="Logo HSJD" style="width: 60%;display: inline-block;"></a>
                </div>
            </div>
            <ul class="list-inline text-center">
                <li class="list-inline-item"><a href="https://www.irsjd.org/en/legal-notice-and-terms-of-use/" target="_blank" rel="noopener noreferrer">Legal notice and terms of use</a></li>
                <li class="list-inline-item"><a href="https://www.irsjd.org/en/privacy-policy/" target="_blank" rel="noopener noreferrer">Privacy policy</a></li>
            </ul>
        </div>
    </div>
</footer>

<!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

<script>
    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();

        $('#btn-copy').on('click', function() {
            $(this).tooltip('hide').attr('data-original-title', 'Copied!').tooltip('show');
        });
    });
</script>

</body>
</html>